# Generated by Django 3.2.7 on 2022-01-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='org_phone',
        ),
        migrations.AddField(
            model_name='client',
            name='BIK',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='БИК'),
        ),
        migrations.AddField(
            model_name='client',
            name='IDN',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='client',
            name='UGNS',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='УГНС'),
        ),
        migrations.AddField(
            model_name='client',
            name='adress',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='client',
            name='bank',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='client',
            name='payment_account',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Расчтный-счет'),
        ),
    ]
