# Generated by Django 3.2.7 on 2021-12-22 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название категории')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=' ', max_length=100)),
                ('remainder', models.FloatField(default=0, verbose_name='Остаток')),
                ('amount', models.IntegerField(default=0, verbose_name='Количество')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(blank=True, choices=[('Белый', 'Белый'), ('Черный', 'Черный'), ('Серый', 'Серый'), ('Красный', 'Красный'), ('Розовый', 'Розовый'), ('Фиолетовый', 'Фиолетовый'), ('Оранжевый', 'Оранжевый'), ('Зеленый', 'Зеленый'), ('Синий', 'Синий'), ('Голубой', 'Голубой'), ('Бирюзовый', 'Бирюзовый'), ('Желтый', 'Желтый'), ('Коричневый', 'Коричневый')], max_length=20, null=True, verbose_name='Цвет')),
                ('shade', models.CharField(default=0, max_length=10, verbose_name='Оттенок')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_category', to='warehouse.category', verbose_name='Категория')),
            ],
        ),
    ]
