# Generated by Django 3.2.7 on 2021-11-19 08:32

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='warehouse.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_category', to='warehouse.category')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('color', models.CharField(blank=True, choices=[('Белый', 'Белый'), ('Черный', 'Черный'), ('Серый', 'Серый'), ('Красный', 'Красный'), ('Розовый', 'Розовый'), ('Фиолетовый', 'Фиолетовый'), ('Оранжевый', 'Оранжевый'), ('Зеленый', 'Зеленый'), ('Синий', 'Синий'), ('Голубой', 'Голубой'), ('Бирюзовый', 'Бирюзовый'), ('Желтый', 'Желтый'), ('Коричневый', 'Коричневый')], max_length=20, null=True)),
                ('shade', models.CharField(default=0, max_length=10)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_category', to='warehouse.category')),
            ],
        ),
    ]
