# Generated by Django 3.2.7 on 2021-12-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20211222_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.CharField(blank=True, choices=[('Акрил', 'Акрил'), ('Форекс', 'Форекс'), ('Самоклеящаяся пленка.', 'Самоклеящаяся пленка.'), ('Светодиоды', 'Светодиоды'), ('Метал ', 'Метал'), ('Другое', 'Другое')], max_length=50, null=True, verbose_name='Категория'),
        ),
    ]
