# Generated by Django 3.2.7 on 2021-12-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_material_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
    ]
