# Generated by Django 3.2.7 on 2021-12-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_alter_material_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='shade',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Оттенок'),
        ),
    ]
