# Generated by Django 3.2.7 on 2022-01-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_remove_material_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='reorder_level',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
