# Generated by Django 3.2.7 on 2022-01-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_invoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.RemoveField(
            model_name='material',
            name='issue_by',
        ),
        migrations.RemoveField(
            model_name='material',
            name='issue_to',
        ),
        migrations.RemoveField(
            model_name='material',
            name='receive_by',
        ),
        migrations.RemoveField(
            model_name='material',
            name='reorder_level',
        ),
        migrations.AlterField(
            model_name='material',
            name='issue_quantity',
            field=models.IntegerField(blank=True, default='0', null=True, verbose_name='Отнять материал'),
        ),
        migrations.AlterField(
            model_name='material',
            name='receive_quantity',
            field=models.IntegerField(blank=True, default='0', null=True, verbose_name='Добавить материал'),
        ),
    ]
