# Generated by Django 3.2.7 on 2022-01-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_auto_20220113_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True, unique=True),
        ),
    ]
