# Generated by Django 3.2.7 on 2021-12-22 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import orders.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerBlank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d', validators=[orders.validators.validate_file_extension], verbose_name='Файл')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('status', models.CharField(blank=True, choices=[('Обычный', 'Обычный'), ('Срочный', 'Срочный')], default='Обычный', max_length=20, null=True, verbose_name='Статус')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн')),
                ('condition', models.CharField(blank=True, choices=[('Не начато', 'Не начато'), ('В процессе', 'В процессе'), ('Завершено', 'Завершено'), ('Отменено', 'Отменено'), ('На расмотрении', 'На расмотрении')], default='Не начато', max_length=20, null=True, verbose_name='Состояние')),
                ('worker', models.CharField(blank=True, choices=[('Менеджер', 'Менеджер'), ('Дизайнер', 'Дизайнер'), ('Печать', 'Печать'), ('Станок', 'Станок'), ('Цех', 'Цех'), ('Цех и Печать', 'Цех и Печать'), ('Поставщик', 'Поставщик')], max_length=20, null=True, verbose_name='Отправить')),
                ('order', models.CharField(blank=True, choices=[('Банер', 'Банер'), ('Вывезка', 'Вывезка'), ('Самоклейка', 'Самоклейка'), ('Фото-бумага', 'Фото-бумага'), ('Постер', 'Постер'), ('Буклетница', 'Буклетница'), ('Другое', 'Другое')], max_length=20, null=True, verbose_name='Тип заказа')),
                ('print', models.BooleanField(default=False)),
                ('design', models.BooleanField(default=False)),
                ('machine', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.client', verbose_name='Клиент')),
            ],
        ),
    ]
