# Generated by Django 3.2.7 on 2021-12-06 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerblank',
            name='files',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='managerblank',
            name='status',
            field=models.ForeignKey(blank=True, default='Обычный', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.status'),
        ),
    ]
