# Generated by Django 3.2.7 on 2022-01-05 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_invoice'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerblank',
            name='amount_wasted_material',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='managerblank',
            name='wasted_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.material', verbose_name='Затраченый материал'),
        ),
        migrations.AlterField(
            model_name='managerblank',
            name='worker',
            field=models.CharField(blank=True, choices=[('Менеджер', 'Менеджер'), ('Дизайнер', 'Дизайнер'), ('Печать', 'Печать'), ('Станок', 'Станок'), ('Цех', 'Цех'), ('Цех и Печать', 'Цех и Печать'), ('Поставщик', 'Поставщик')], max_length=20, null=True, verbose_name='Отправить'),
        ),
    ]
