# Generated by Django 3.2.7 on 2022-01-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20220105_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerblank',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во'),
        ),
    ]
