# Generated by Django 3.2.7 on 2021-12-06 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20211206_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='condition',
            field=models.CharField(default='Не начато', max_length=20),
        ),
        migrations.AlterField(
            model_name='managerblank',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.condition'),
        ),
        migrations.AlterField(
            model_name='managerblank',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.status'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(default='Обычный', max_length=20),
        ),
    ]
