# Generated by Django 3.2.7 on 2021-12-06 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20211206_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerblank',
            name='status',
            field=models.ForeignKey(default=[0], null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.status'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
