# Generated by Django 3.2.7 on 2022-01-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20220106_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerblank',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
