# Generated by Django 3.2.7 on 2022-01-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_managerblank_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerblank',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
    ]
