# Generated by Django 3.2.7 on 2021-12-06 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20211206_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerblank',
            name='condition',
            field=models.ForeignKey(blank=True, default=[1], null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.condition'),
        ),
    ]
